In [29]:
import pandas as pd
data=pd.DataFrame({'name':['anu','binnu','srinu','anu'],
      'age':[12,19,67,12]})

print(data.duplicated())
print(data.drop_duplicates())

0    False
1    False
2    False
3     True
dtype: bool
    name  age
0    anu   12
1  binnu   19
2  srinu   67

In [30]:
employee={'Name':['srinivas','sushanth','saritha','binnu','lucky'],
        'salary':[100000,150000,70000,800000,60000]}
solution=pd.DataFrame(employee)
print(solution)

       Name  salary
0  srinivas  100000
1  sushanth  150000
2   saritha   70000
3     binnu  800000
4     lucky   60000

In [42]:
print([solution['salary']>70000])

[0     True
1     True
2    False
3     True
4    False
Name: salary, dtype: bool]

In [47]:
print(solution.query('salary>70000'))

       Name  salary
0  srinivas  100000
1  sushanth  150000
3     binnu  800000

In [56]:
print(solution.query('salary>50000 and salary<70000'))

    Name  salary
4  lucky   60000

In [58]:
movie={'name':['majili','pagal','darling','fidaa']}
review=pd.DataFrame(movie)
print(review)

      name
0   majili
1    pagal
2  darling
3    fidaa

In [59]:
print(review.sample(3))

      name
2  darling
3    fidaa
0   majili

In [60]:
review.sample(3)

     name
1   pagal
3   fidaa
0  majili

In [78]:
review.sample(2,random_state=1)

      name
3    fidaa
2  darling

In [79]:
review.sample(4,random_state=0)

      name
2  darling
3    fidaa
1    pagal
0   majili

In [80]:
data={'date':['2025-02-18','2026-05-20','2010-03-18','2002-09-13']}
result=pd.DataFrame(data)
print(result)
result['date']=pd.to_datetime(result['date'])

         date
0  2025-02-18
1  2026-05-20
2  2010-03-18
3  2002-09-13

In [81]:
result['date']=pd.to_datetime(result['date'])
result['date'].dt.year

0    2025
1    2026
2    2010
3    2002
Name: date, dtype: int32

In [82]:
result['date']=pd.to_datetime(result['date'])
result['date'].dt.month

0    2
1    5
2    3
3    9
Name: date, dtype: int32